import type { Language, Difficulty } from "@/types";
import { topicTexts } from "@/data/wordpacks";

// Text data for typing tests - organized by language and difficulty
// Each difficulty has 10 topics, randomly selected during tests
const sampleTexts: Record<Language, Record<Difficulty, string[]>> = {
  uz: {
    easy: [      // Salomatlik
      "har kun ertalab tur va suv ich tana uchun suv juda kerak agar suv kam yetsa tana holdan ketadi bosh ham charchaydi shu uchun har soat bir oz suv ichish kerak suv toza kerak iliq suv ham yaxshi tana suv bilan ishlaydi qon ham suv bilan harakat qiladi miya ham suv talab qiladi salomat qolish uchun suv ichish odat qiling har kun sakkiz stakan ichish yetarli tashqarida harakat qilish ham salomatlikka foyda beradi sabzavot va meva yeyish tana uchun kerakli quvvat beradi charchagan paytda dam olish ham muhim",
      // Bilim
      "kitob bilim beradi har kun bir oz kitob ochish kerak kitob yangi fikr beradi bilim ortadi tez yozish ham kitob bilan aloqador kitobdan bilim olgan odam ancha biladi gap boyligi ortadi kitob birodar kabi tanho qolsang kitob bor u senga yordam beradi yangi dunyo ochadi kitob bilan yashash odat qiling har kuni besh daqiqa ham yetarli kutubxonaga borish ham foydali u yerda minglab kitob topasan bilib olgan narsangni birodaringga aytib ber shunda yaxshi eslab qolasan yozib borish ham bilimni mustahkamlaydi",
      // Ish va mehnat
      "ish qilish hayotni yaxshi qiladi har kun oz oz ish qilsang katta ish chiqadi sabr bilan mehnat qilgan odam yutuqqa yetadi ish qiyin kelsa ham davom et erta meva yetiladi dangasa odam hech nima qila olmaydi mehnat kuch beradi ruh ham kuchayadi ishla va umid qilma ishla va natijani kuzat mehnat qilgan inson baxtli yashaydi rejasiz ish natija bermaydi shu uchun avval reja tuz keyin ishga kirish jamoa bilan ishlash yakka ishlashdan samarali chunki birgalikda katta ish bajarish oson",
      // Tabiat
      "tabiat bizni qurshab turadi daraxt havo beradi suv hayot beradi yer oziq beradi tabiatni asra iflos qilma chiqindi tashlama tabiat toza kelsa biz ham salomat yashaymiz qush sayraydi gul ochadi havo toza keladi tabiat chiroyli joy uni saqla kelajak avlod uchun ham tabiat kerak har kun tabiatga chiq dam ol nafas ol daraxt ekish yerni yashil qiladi va havoni tozalaydi daryolar va hovuzlar hayvonlarga uy beradi tabiatni asrash bizning burchimiz har kishi ozgina harakat qilsa katta natija chiqadi",
      // Odatlar
      "yaxshi odat hayotni oson qiladi har kun bir xil vaqtda tur bir xil vaqtda yot tana odat bilan ishlaydi agar tartib yaxshi kelsa tana ham salomat keladi yomon odat esa zararli agar yomon odat kelsa uni tashla yaxshi odat qabul qil bir oy davom etsa odat shakllanadi sabr bilan davom et natija albatta keladi yaxshi odat boylik ertalab erta turish kun davomida kuch beradi kechqurun reja tuzish ertangi ishni osonlashtiradi kichik qadamlar katta yangilanishga olib boradi",
      // Uyqu
      "yaxshi uyqu salomatlikning asosi har kun vaqtida yotish va vaqtida turish kerak agar kam uxlasang tana horiydi miya yaxshi ishlamaydi diqqat pasayadi yotishdan oldin telefondan uzoqlash kitobni varaqla yoki dam ol xona xira va salqin kerak uyqu yetti yoki sakkiz soat yetadi oldidan juda ovqatlanma chala uxlash zararli yaxshi uyqu ertangi kunga kuch beradi tunda yorqin nurdan uzoq turish miyani tinch qiladi issiq suvda yuvinish tanani yumshatadi hafta oxirida ham bir xil vaqtda uxlash foydali",
      // Birodarlik
      "birodar hayotda eng qimmat boylik yaxshi birodar quvonchda quvonadi tashvishda yordam beradi birodaringga rost gapir vada bersang bajar uni hurmat qil va tinglashga harakat qil agar birodaring xato qilsa dushmanga aylanma durust gap ayt yaxshilik tila birodarlik yillar bilan chuqurlashadi yangi birodar topish oson eski birodar topish qiyin shu uchun har bir birodaringni qadrla qiyin kunda yoningda turgan inson eng qadrli birodar hisoblanadi uzoqda yashasa ham aloqani uzma tez tez xabar ber yoki aloqa qil kichik xatolarni kechir chunki hech kim mukammal emas",
      // Oila
      "oila eng qadrli joy uy ichida sevgi va mehr yashasin ota va ona bolasiga vaqt ajratsin gaplashsin tinglasin ovqat birga yeyilsin har kuni bola bilan suhbatlashing qiyin paytda yonida turing oilada hurmat va sabr yashasin yangi avlod oiladan bilim oladi shu uchun namuna bering oila kuchli kelsa hayot ham kuchli keladi har bir kun uchun shukur qilish kerak dam olish kunlarida oila bilan birga vaqt sarflash yaxshi odat katta yoshdagilarni hurmat qilish bolalarga yaxshi natija beradi kichik bayramlarni ham birga nishonlash oilani yanada mustahkamlaydi",
      // Sport
      "sport tana va aqlni mustahkamlaydi har kun bir oz harakat qilish kerak yugurish piyoda yurish yoki suzish foydali sport stress kamaytiradi kayfiyatni yaxshilaydi tana salomat kelsa ish ham yaxshi yurishadi sportni odat qilib har kun davom et yarim soat ham kifoya kuchli mushak va chidamli yurak shu mashqlardan keladi yangi kun uchun energiya beradi sportga vaqt ajrating mashq oldidan tanani isitish shikast xavfini kamaytiradi jamoaviy sport birodarlik hissini kuchaytiradi mashq paytida suv ichib turish toliqishni kamaytiradi",
      // Sayohat
      "sayohat dunyoni bilishning eng yaxshi usuli yangi joyga borsang yangi narsalarni bilib olasan tabiatni kuzat odamlar bilan tanish taomlarni tatib boq har shahar va qishloqning alohida qiziqligi bor sayohat oldin reja tuz kerakli narsalarni ol pul tejab harajat qil rasmga ol esda saqlash uchun til bilmasang ham imo-ishora bilan gaplashish mumkin sayohat fikrni ochadi qalbni yangilaydi yengil yuk bilan safar qilish qulay keladi mahalliy transportdan foydalanish shaharni yaqindan tanishtiradi yangi tajriba doim kutilmagan sevinch olib keladi",
],
    medium: [
      // Sog'liq va sport
      "Sog'lom hayot uchun har kuni jismoniy mashqlar qilish muhim, chunki tana harakatga muhtoj. Agar muntazam sport bilan shug'ullansangiz, yurak kuchli bo'ladi va energiya oshadi. Ertalabki yugurish yoki sayr kayfiyatni yaxshilaydi, stress kamayadi. Mashqdan keyin tana dam oladi va mushaklar tiklanadi. Sport faqat jism uchun emas, ruh uchun ham foydali. Har hafta kamida uch marta mashq qiling, natija sezilarli bo'ladi. To'g'ri ovqatlanish va yetarli dam olish mashqning samarasini yanada oshiradi. Sabr bilan davom etgan odam albatta yaxshi natijaga erishadi.",
      // Ta'lim va o'rganish
      "O'rganish jarayoni butun umr davom etadi, chunki bilim chegarasiz. Har kuni yangi narsa o'rgansangiz, miya faol ishlaydi. Kitob o'qish, video ko'rish yoki amaliyot qilish orqali bilim oshadi. Muhimi, o'rgangan narsani takrorlash kerak, chunki takror xotiraga yordam beradi. O'qituvchi yoki murabbiy yo'l ko'rsatadi, lekin mehnat o'zingizdan. Ta'lim kelajakka sarmoya, uni qadrlab o'rganing. Har inson o'ziga mos o'rganish uslubini topishi kerak, ba'zilar ko'rish orqali, ba'zilar yozish orqali yaxshiroq eslab qoladi. Muntazam mashq qilish esa har qanday ko'nikmani mustahkamlaydi.",
      // Vaqtni boshqarish
      "Vaqt eng qimmat boylik, chunki uni qaytarib bo'lmaydi. Har kuni rejali ishlasangiz, vaqt tejab qolinadi. Muhim ishlarni avval bajaring, kichik ishlar keyin. Telefon va ijtimoiy tarmoqlar ko'p vaqt oladi, ularni chegaralang. Ertalab eng samarali vaqt, murakkab ishlarni o'shanda qiling. Kechqurun esa dam oling va ertangi kunga tayyorlaning. Vaqtni to'g'ri ishlatsangiz, hayot tartibli bo'ladi. Kichik tanaffuslar diqqatni yangilaydi va charchoqni kamaytiradi. Har kunni oldindan rejalashtirgan odam vaqtini yo'qotmaydi va maqsadiga tezroq yetadi.",
      // Maqsad qo'yish
      "Maqsadsiz hayot yo'nalishsiz kemaga o'xshaydi. Aniq maqsad qo'ying va har kuni unga qarab yuring. Katta maqsadni kichik qismlarga bo'ling, shunda osonroq. Har hafta natijani tekshiring, agar orqada qolsangiz, tezlating. Maqsad yozilgan bo'lsin, ko'z oldingizda tursin. Qiyinchilik bo'lsa ham to'xtamang, chunki sabr muvaffaqiyat keltiradi. Maqsadga yetgan inson o'ziga ishonadi va yangi cho'qqilarni egallaydi. Maqsadni boshqalar bilan baham ko'rish javobgarlikni oshiradi va davom etish uchun qo'shimcha kuch beradi. Har kichik yutuq katta maqsad tomon muhim qadamdir.",
      // Sog'lom ovqatlanish
      "To'g'ri ovqatlanish sog'liq asosi, chunki tana ozuqa bilan ishlaydi. Ko'proq sabzavot va meva iste'mol qiling, ular vitamin beradi. Tez taom va shirinlikdan saqlaning, ular zararli. Suv ko'p iching, choy va qahva ham bo'lishi mumkin, lekin cheklangan. Ovqatni sekin yeng, chaynab yutish hazm uchun yaxshi. Kechqurun og'ir ovqat yemang, uxlash qiyin bo'ladi. Sog'lom ovqat energiya beradi va kasallikdan saqlaydi. Yog'li va qovurilgan ovqatni kamaytirish yurak salomatligiga foyda qiladi. Kuniga bir necha marta oz-oz ovqatlanish esa metabolizmni yaxshilaydi.",
      // Texnologiya
      "Zamonaviy texnologiya hayotni sezilarli darajada o'zgartirdi. Smartfon va internet orqali biz bir necha soniyada ma'lumot olamiz, do'stlar bilan aloqa qilamiz va yangi narsa o'rganamiz. Onlayn kurslar uydan turib bilim olish imkonini berdi. Lekin ekran oldida ko'p o'tirish salomatlikka zarar yetkazadi. Texnologiyadan foydali maqsadlarda foydalansangiz, vaqt va kuch tejaladi. Doimo yangi vositalarni o'rganib boring. Ijtimoiy tarmoqlardan oqilona foydalanish diqqatni chalg'itishning oldini oladi. Har qanday qurilma ish uchun qulaylik yaratadi, lekin uni to'g'ri boshqarish inson zimmasida qoladi.",
      // Til o'rganish
      "Yangi til o'rganish sabr va tartib talab qiladigan jarayon. Har kuni kamida o'n daqiqa mashq qilsangiz, so'z boyligi sezilarli darajada oshadi. Tilni eshitish, o'qish, gapirish va yozish to'rtta muhim ko'nikma birga rivojlanishi kerak. Mahalliy so'zlovchilar bilan suhbatlashish eng tezkor yo'l. Filmlar va qo'shiqlar orqali ham o'rganish foydali. Doimiy mashq orqali siz albatta maqsadingizga erishasiz. Yangi so'zlarni jumla ichida ishlatish ularni yodda tez saqlaydi. Xato qilishdan qo'rqmang, chunki har bir xato tilni yaxshiroq egallashga yordam beradi.",
      // Stress kamaytirish
      "Zamonaviy hayotda stress muqarrar hodisa, ammo uni kamaytirish mumkin. Chuqur nafas olish va meditatsiya asab tizimini tinchlantiradi. Tabiatda sayr qilish va quyosh nuri kayfiyatni yaxshilaydi. Muammoni qog'ozga yozib chiqsangiz, u kichikroq ko'rinadi. Yetarli uyqu va sog'lom ovqat stress gormonlarini kamaytiradi. Yaqinlar bilan suhbat qalbni yengillashtiradi. Sport bilan shug'ullanish ham tashvishni kamaytiradigan eng samarali usuldir. Kuniga bir necha daqiqa jim o'tirib nafas olish miyani tinchlantiradi. Ortiqcha ishni bo'lib-bo'lib bajarish esa his qilinadigan bosimni sezilarli kamaytiradi.",
      // Yangi ko'nikmalar
      "Yangi ko'nikma egallash shaxsiy rivojlanishning eng muhim qismi. Har bir o'rgangan mahorat sizga yangi imkoniyatlar yaratadi. Boshlang'ich bosqichda sabr juda muhim, chunki birinchi natijalar tezda ko'rinmaydi. Internetda bepul darslar va video qo'llanmalar mo'l, faqat izlang. Har kuni atigi yarim soat mashq qilsangiz, oy ichida sezilarli taraqqiyot bo'ladi. Yangi mahorat karyera imkoniyatlarini ham kengaytiradi va hayotni boyitadi. Boshqalardan maslahat olish va mustaqil mashq qilish birga borganda o'rganish tezlashadi. Yangi mahorat egallagan inson o'ziga bo'lgan ishonchini ham mustahkamlaydi.",
      // Pul tejash
      "Pulni to'g'ri boshqarish sog'lom hayotning asosi hisoblanadi. Har oy daromadingizning kamida o'n foizini jamg'arish odatga aylantiring. Keraksiz xaridlardan saqlaning va shoshilinch qarorlardan voz keching. Xarajatlaringizni yozib boring, shunda pul qaerga ketayotganini bilasiz. Xaridga ro'yxat tuzib chiqing, bozorda faqat shu ro'yxat asosida xarid qiling. Zaxira fond yaratish moliyaviy erkinlikka olib boradi va xotirjamlik beradi. Kichik xarajatlarni ham kuzatib borish katta tejamkorlikka olib keladi. Pulni oqilona sarflagan inson kelajakda kutilmagan qiyinchiliklarga ham tayyor bo'ladi.",
    ],
    hard: [
      // Produktivlik
      "\"DeepWork\" metodologiyasi intellektual mehnatni samarali tashkil etishga yo'naltirilgan, chunki zamonaviy dunyoda diqqatni jamlash tobora qiyinlashmoqda. Tadqiqotlarga ko'ra, multitasking samaradorlikni 40% ga kamaytiradi. Shuning uchun 2 soatlik fokuslanish sessiyalari, \"Pomodoro\" texnikasi va raqamli detoks kabi strategiyalar ahamiyatga ega. Natijadorlikni oshirish uchun WPM ko'rsatkichini kuzatish va haftalik retrospektiva o'tkazish tavsiya etiladi. Ish joyida bildirishnomalarni vaqtincha o'chirish ham diqqatni jamlashga yordam beradi. Har bir mutaxassis o'z eng samarali vaqtini aniqlab, murakkab vazifalarni aynan o'sha soatlarga rejalashtirishi kerak. Uzluksiz ish rejimi charchoqni oshiradi, shuning uchun har 90 daqiqada qisqa tanaffus qilish tavsiya etiladi.",
      // Sun'iy intellekt
      "\"ArtificialIntelligence\" texnologiyasi zamonaviy innovatsiyalarning asosiy yo'nalishi hisoblanadi. Machine Learning va Neural Networks orqali kompyuterlar murakkab masalalarni hal etishga qodir. OpenAI, Google va boshqa gigantlar bu sohada 10 milliard dollardan ortiq sarmoya kiritmoqda. AI tibbiyot, moliya va UX dizaynida inqilobiy o'zgarishlar yaratmoqda, ammo etik muammolar ham muhokama qilinmoqda. Bundan tashqari, ko'plab kompaniyalar mijozlarga xizmat ko'rsatishda chatbotlardan foydalanmoqda, bu esa xarajatlarni sezilarli darajada kamaytirmoqda. Mutaxassislarning fikricha, keyingi o'n yil ichida ko'plab kasblar sun'iy intellekt yordamida butunlay o'zgarishi mumkin. Shu bilan birga, mualliflik huquqi va ma'lumotlar maxfiyligi masalalari ham dolzarb bo'lib qolmoqda.",
      // Moliyaviy savodxonlik
      "\"FinancialLiteracy\" shaxsiy moliyani boshqarish mahorati sifatida zamonaviy hayotning ajralmas qismidir. Byudjetlashtirish, investitsiya va passiv daromad tushunchalari har bir inson uchun muhim. Mutaxassislar daromadning 20% ini jamg'arish va 3-6 oylik zaxira fondini tavsiya qiladi. Compound Interest prinsipi orqali uzoq muddatda kapital sezilarli o'sadi. Aksariyat odamlar yoshligida jamg'armani boshlamaydi, natijada ular kelajakda moliyaviy qiyinchiliklarga duch keladi. Har oyning boshida byudjet tuzish va xarajatlarni toifalarga ajratish moliyaviy nazoratni osonlashtiradi. Qarzdan qochish va faqat zarur narsalarga xarid qilish uzoq muddatli barqarorlik uchun muhim. Investitsiya qilishdan oldin bozorni chuqur o'rganish esa xatarlarni sezilarli kamaytiradi.",
      // Psixologiya
      "\"EmotionalIntelligence\" tushunchasi shaxslararo munosabatlar va kasbiy muvaffaqiyatda muhim rol o'ynaydi. EQ ko'rsatkichi IQ dan ko'ra hayotiy natijalarni yaxshiroq bashorat qiladi. O'z-o'zini anglash, empatiya va stressni boshqarish kabi komponentlar rivojlantirilishi mumkin. Tadqiqotlar yuqori EQ ga ega insonlar 58% ko'proq daromad olishini ko'rsatadi. Bolalikda his-tuyg'ularni tanib olish va ularni to'g'ri ifodalash o'rgatilsa, kattalikda muvaffaqiyatli munosabatlar qurish osonlashadi. Ish joyida yuqori emotsional intellektga ega rahbarlar jamoa a'zolarining ishonchini tezroq qozonadi. O'zgalarning holatini tushunish, ziddiyatlarni tinch yo'l bilan hal qilishga ko'maklashadi. Muntazam o'z-o'ziga tahlil berish orqali har kim emotsional intellektini asta-sekin rivojlantirishi mumkin.",
      // Raqamli marketing
      "\"DigitalMarketing\" strategiyasi zamonaviy biznesning asosiy tarkibiy qismi hisoblanadi. SEO, SMM va Content Marketing orqali brendlar millionlab auditoriyaga yetib boradi. A/B Testing va Analytics vositalari kampaniya samaradorligini 3x ga oshirishi mumkin. ROI ni hisoblash va KPI larni kuzatish professional marketerning asosiy vazifasi, chunki Data-Driven qarorlar muvaffaqiyatni ta'minlaydi. E-pochta orqali marketing hamon eng arzon va samarali usullardan biri hisoblanadi, chunki u to'g'ridan-to'g'ri mijoz bilan aloqa o'rnatadi. Ijtimoiy tarmoqlardagi bloggerlar bilan hamkorlik qilish yosh auditoriyaga tezroq yetib borishga yordam beradi. Muvaffaqiyatli kampaniya uchun avval maqsadli auditoriyani aniq belgilash, so'ngra kontentni shunga moslashtirish zarur.",
      // Kiberxavfsizlik
      "\"CyberSecurity\" sohasida ma'lumotlarni himoya qilish asosiy vazifa hisoblanadi. Two-Factor Authentication va kuchli parollar hisoblarni buzg'unchidan saqlaydi. Tadqiqotlarga ko'ra, hujumlarning 80% i insoniy xato natijasida sodir bo'ladi. Phishing va Ransomware kabi tahdidlar yiliga 6 trillion dollar zarar keltiradi. Encryption va Regular Backup yagona ishonchli mudofaa yo'lidir. Shu sababli har bir foydalanuvchi murakkab va noyob parollardan foydalanishi, hamda ularni muntazam yangilab turishi kerak. Notanish havolalarni bosishdan saqlanish va elektron pochta manzilini diqqat bilan tekshirish oddiy, ammo samarali himoya usuli hisoblanadi. Kompaniyalar xodimlarga muntazam ravishda kiberxavfsizlik bo'yicha ta'lim berishi, ehtimoliy tahdidlarni oldindan aniqlashga yordam beradi.",
      // Qayta tiklanuvchan energiya
      "\"RenewableEnergy\" tarmog'i iqlim o'zgarishi bilan kurashda hal qiluvchi rol o'ynaydi. Quyosh va shamol energiyasi 2024-yilda global elektr ta'minotining 30% ini tashkil qildi. Solar paneli texnologiyasining narxi so'nggi o'n yilda 90% ga arzonlashdi. Net-Zero maqsadiga erishish uchun investitsiyalar yiliga 4 trillion dollarga yetishi kerak. Ko'plab davlatlar qayta tiklanuvchan manbalarga o'tishni tezlashtirish uchun soliq imtiyozlari va subsidiyalar taqdim etmoqda. Shamol turbinalari va quyosh panellarining narxi tushishi bilan, oddiy uy xo'jaliklari ham bu texnologiyadan foydalanish imkoniyatiga ega bo'lmoqda. Energiya saqlash batareyalari sohasidagi rivojlanish esa quyosh botgandan keyin ham uzluksiz elektr ta'minotini kafolatlaydi.",
      // Masofaviy ish
      "\"RemoteWork\" modeli korporativ madaniyatni sezilarli darajada o'zgartirdi. Pandemiyadan keyin 35% mutaxassis uydan turib ishlashni davom ettirdi. Slack, Zoom va AsyncCommunication vositalari jamoa hamkorligini ta'minlaydi. Lekin mehnat va dam olish chegarasi yo'qolgani Burnout risklarini 25% ga oshirdi. Vaqt boshqaruvi va aniq KPI lar muvaffaqiyatning asosiy omillaridir. Muntazam video-uchrashuvlar tashkil qilish jamoa a'zolari orasidagi masofani kamaytiradi va ishonchni mustahkamlaydi. Uy sharoitida alohida ish burchagini tashkil etish esa diqqatni jamlashga sezilarli yordam beradi. Ko'pgina kompaniyalar endilikda gibrid ish rejimini afzal ko'rmoqda, bu esa xodimlarga ham moslashuvchanlik, ham jamoaviy aloqani saqlab qolish imkonini beradi.",
      // Raqamli tibbiyot
      "\"HealthTech\" sektori tibbiy xizmatlarni butunlay yangi shaklga keltirdi. Telemedicine va WearableDevices bemorlarning salomatligini real vaqtda kuzatish imkonini berdi. AI-Diagnostika tizimlari saraton aniqlash aniqligini 95% ga yetkazdi. Sog'liqni saqlash sohasiga investitsiyalar 2025-yilda 600 milliard dollardan oshdi. Personalized Medicine kelajakdagi asosiy yo'nalish hisoblanadi. Masofadan turib shifokor bilan maslahatlashish imkoniyati qishloq joylarida yashovchilar uchun ayniqsa foydali bo'lmoqda. Aqlli soatlar va fitnes brasletlari yurak urishi, uyqu sifati va jismoniy faollikni doimiy nazorat qilishga yordam beradi. Bu ma'lumotlar shifokorlarga bemorning holatini yanada aniqroq baholash va kasallikni erta bosqichda aniqlash imkonini beradi. Kelajakda sun'iy intellekt yordamida shaxsiylashtirilgan davolash rejalari yanada keng tarqalishi kutilmoqda.",
      // Iqlim o'zgarishi
      "\"ClimateChange\" muammosi insoniyat oldidagi eng jiddiy sinovlardan biridir. CarbonFootprint kamaytirish va Sustainable Practices joriy etish kechiktirib bo'lmaydi. Global harorat 1850-yildan beri 1.2°C ga oshdi va 2050-yilga 2°C ortishi kutilmoqda. EV (Electric Vehicle) sotuvi 2024-yilda 18% ga oshdi. Yashil iqtisodiyot kelajakning yagona yo'lidir. Muzliklarning erishi dengiz sathining ko'tarilishiga sabab bo'lmoqda, bu esa qirg'oq bo'yidagi shaharlarga jiddiy xavf tug'dirmoqda. Ko'plab davlatlar daraxt ekish dasturlarini kengaytirib, o'rmonlarni tiklashga harakat qilmoqda. Har bir inson kundalik hayotda plastik iste'molini kamaytirish va jamoat transportidan foydalanish orqali ham hissa qo'sha oladi. Kelajak avlodlar uchun toza sayyorani saqlash umumiy javobgarlik hisoblanadi.",
    ],
  },
  en: {
    easy: [
      // Health
      "water is life and you need it each day your body needs water to work well if you drink less you feel tired and weak try to drink eight cups a day it helps your skin your brain and your heart water keeps you fresh and full of life make it a habit to drink more clean water is best for your body stay well and drink water every day",
      // Learning
      "to learn is to grow and we can learn each day read a book or watch a video that helps you know more your brain loves new facts and ideas when you learn you get smart and wise take notes and review them later this helps you keep what you learn make time to study even if just a bit each day you will see big gains over time a curious mind always finds something new to explore",
      // Work habits
      "work is good for your mind and soul when you work hard you feel proud of what you do start your day with a plan and follow it take small steps and soon big things come your way rest when you need to but do not give up keep your space clean and your mind clear work smart not just hard and life gets easier every task done is a win for you",
      // Nature
      "nature is all around us and it gives us life trees give us air to breathe and shade to rest water flows in rivers and gives life to all spend time outside and feel the fresh air walk in a park or sit by a lake nature helps you relax and feel at peace take care of our earth and keep it clean for us and for those who come after us",
      // Habits
      "good habits make life easy and fun wake up at the same time each day and go to bed on time too eat well and move your body read a bit and rest when tired these small acts add up over time bad habits pull you down but you can change them one step at a time start today and keep going soon you will feel the change in your life",
      // Sleep
      "good sleep is the base of health go to bed and wake up at the same time each day if you sleep too little your body feels tired your brain works slow and focus drops put the phone away before bed read a book or just relax keep the room dark and cool aim for seven or eight hours of sleep good sleep gives you fresh energy for a new day",
      // Friendship
      "a true friend is the most valuable thing in life a good friend shares your joy and helps in hard times never lie to your friend keep your promise show respect and listen with care if a friend makes a mistake do not turn away speak the truth and wish them well friendship grows over years new friends are easy old ones are rare value each friend you have small acts of kindness keep a friendship strong for a long time",
      // Family
      "family is the most precious thing in life let your home be full of love and care parents should give time to their kids talk to them and listen eat meals together each day ask how their day was help them when things are hard show respect and patience kids learn from family be a good example strong family makes life strong say thanks for each day small moments spent together build memories that last a lifetime",
      // Sport
      "sport keeps your body and mind strong move a little every day running walking or swimming all help sport reduces stress and lifts your mood when your body feels good your work goes well too make it a habit to move every day even thirty minutes is enough strong muscles and a healthy heart come from regular practice it gives you fresh energy for a new day so make time for sport",
      // Travel
      "travel is the best way to see the world when you visit a new place you learn new things see nature meet people and try local food every city has its own charm before you travel make a plan pack what you need spend money wisely take photos to keep memories travel opens your mind and refreshes your soul each day brings a new experience and story even a short trip can teach you something you never knew before",
    ],
    medium: [
      // Health and fitness
      "Physical exercise is essential for a healthy lifestyle, because the body needs regular movement to stay strong. When you exercise consistently, your heart becomes stronger and energy levels rise. Morning runs or evening walks improve your mood and reduce stress. After working out, allow your body to rest and recover properly. Fitness benefits both physical and mental health. Try to exercise at least three times per week, and you will notice significant improvements in your overall wellbeing.",
      // Education
      "Learning is a lifelong journey that never truly ends. Every day presents opportunities to gain new knowledge and skills. Reading books, watching educational videos, or practicing hands-on activities all contribute to growth. The key is to review what you learn, because repetition strengthens memory. Teachers and mentors can guide you, but the real effort must come from within. Education is an investment in your future, so value it and pursue it with dedication.",
      // Time management
      "Time is our most valuable resource, because once it passes, we cannot get it back. Planning your day carefully helps you accomplish more tasks efficiently. Prioritize important work first, and handle smaller tasks afterward. Social media and digital distractions consume significant time, so set clear boundaries. Mornings are often the most productive hours for complex work. Evenings should be reserved for rest and preparation for the next day. Small breaks between tasks actually refresh the mind and reduce mistakes.",
      // Goal setting
      "Without clear goals, life can feel like a ship without direction. Set specific objectives and work toward them daily. Break large goals into smaller milestones to make progress manageable. Review your results weekly, and adjust your approach if needed. Write down your goals and keep them visible as constant reminders. Persistence through challenges leads to success. Those who achieve their goals develop confidence and continue reaching for greater heights. Sharing your goals with someone you trust makes it harder to give up.",
      // Nutrition
      "Proper nutrition forms the foundation of good health, because the body relies on quality fuel to function well. Consume plenty of vegetables and fruits for essential vitamins and minerals. Avoid excessive fast food and sugary snacks, as they harm your health. Drink adequate water throughout the day. Eat slowly and chew thoroughly for better digestion. Avoid heavy meals before bedtime, as they disrupt sleep. Healthy eating provides energy and prevents disease.",
      // Technology
      "Modern technology has dramatically changed how we live our daily lives. Through smartphones and the internet, we access information in seconds, communicate with friends across the world, and learn new skills. Online courses make it possible to gain quality education from home. However, too much screen time can harm your health. When you use technology for useful purposes, you save time and energy. Continue learning the latest tools and apps to stay productive.",
      // Language learning
      "Learning a new language requires patience and consistent practice over time. If you study at least ten minutes every day, your vocabulary will grow significantly. Listening, reading, speaking, and writing are four essential skills that must develop together. Conversation with native speakers is the fastest way to improve fluency. Movies and songs in the target language also help build understanding. Through daily practice, you will eventually reach your language goals and gain confidence in communication.",
      // Stress management
      "Stress is an unavoidable part of modern life, but you can effectively reduce its impact. Deep breathing exercises and meditation calm your nervous system remarkably well. Walking in nature and getting sunlight noticeably improves your mood. When you write problems on paper, they often appear smaller. Adequate sleep and healthy food reduce stress hormones. Conversations with loved ones lighten the heart and provide comfort. Regular sports activity is one of the most effective methods for managing anxiety.",
      // New skills
      "Acquiring a new skill is one of the most important aspects of personal development. Every skill you learn opens new opportunities and doors in life. Patience matters most at the beginning stage, because the first results take time to appear. The internet provides countless free tutorials and video lessons, just search for them. If you practice just thirty minutes every day, you will see noticeable progress within a month. New skills also expand career opportunities and enrich your overall life experience.",
      // Saving money
      "Managing your money wisely forms the foundation of a healthy life. Make it a habit to save at least ten percent of your monthly income. Avoid unnecessary purchases and stay away from impulsive financial decisions. Track all your expenses on paper, so you know where your money goes. Make a shopping list before going to the store, and buy only what is on the list. Building an emergency fund leads to financial freedom and peace of mind.",
    ],
    hard: [
      // Productivity
      "\"DeepWork\" methodology focuses on optimizing intellectual labor in an increasingly distracted world. Research indicates that multitasking reduces productivity by approximately 40%, making focused sessions essential. Implementing 2-hour concentration blocks, utilizing the \"Pomodoro\" technique, and practicing digital detox are strategies proven to enhance output. Tracking WPM metrics and conducting weekly retrospectives help professionals continuously improve their workflow efficiency. Turning off notifications at work also helps you focus. Every professional should identify their most productive hours and schedule complex tasks exactly during that time. Continuous work increases fatigue, so a short break every 90 minutes is recommended.",
      // Artificial intelligence
      "\"ArtificialIntelligence\" technology represents the cornerstone of contemporary innovation. Through Machine Learning and Neural Networks, computers can solve increasingly complex problems. Industry giants including OpenAI and Google have invested over 10 billion dollars in AI development. These technologies are creating revolutionary changes in healthcare, finance, and UX design, while simultaneously raising important ethical considerations that society must address. Moreover, many companies now use chatbots for customer service, which significantly reduces costs. Experts believe that within the next ten years many professions could be completely transformed by artificial intelligence. At the same time, copyright and data privacy issues remain pressing concerns.",
      // Financial literacy
      "\"FinancialLiteracy\" encompasses the essential skills required for effective personal finance management. Understanding budgeting, investment strategies, and passive income concepts is crucial for everyone. Financial experts recommend saving 20% of income and maintaining 3-6 months of emergency reserves. The Compound Interest principle demonstrates how capital grows significantly over extended timeframes when properly managed. Most people do not start saving early in life, which often leads to financial difficulties later on. Creating a monthly budget and categorizing expenses makes financial control much easier. Avoiding debt and only purchasing what is necessary matters for long-term stability. Studying the market thoroughly before investing significantly reduces risk.",
      // Psychology
      "\"EmotionalIntelligence\" plays a critical role in interpersonal relationships and professional achievement. Studies suggest EQ predicts life outcomes more accurately than traditional IQ measurements. Components including self-awareness, empathy, and stress management can be systematically developed. Research demonstrates that individuals with higher EQ earn approximately 58% more income compared to their lower-scoring counterparts. When emotional awareness is taught early in childhood, building successful relationships becomes easier in adulthood. Leaders with high emotional intelligence earn their team's trust faster. Understanding others' feelings helps resolve conflicts peacefully. Regular self-reflection allows anyone to gradually strengthen their emotional intelligence.",
      // Digital marketing
      "\"DigitalMarketing\" strategy constitutes a fundamental component of contemporary business operations. Through SEO, SMM, and Content Marketing, brands reach millions of potential customers globally. A/B Testing and Analytics tools can improve campaign effectiveness by 3x or more. Calculating ROI and monitoring KPIs represents the core responsibility of professional marketers, as Data-Driven decisions ultimately determine success. Email marketing remains one of the cheapest and most effective methods, because it builds a direct connection with the customer. Partnering with social media influencers helps brands reach younger audiences faster. A successful campaign requires clearly defining the target audience first, then tailoring the content accordingly.",
      // Cyber security
      "\"CyberSecurity\" domain considers data protection as the primary mission of any modern organization. Two-Factor Authentication and strong passwords protect accounts from hackers effectively. According to research, approximately 80% of cyber attacks happen due to human error. Phishing and Ransomware threats cause damages exceeding 6 trillion dollars annually. Encryption combined with regular backups remains the only truly reliable defense strategy. That is why every user should use strong, unique passwords and update them regularly. Avoiding suspicious links and carefully checking email addresses is a simple yet effective defense. Companies that regularly train employees on cybersecurity help detect potential threats earlier.",
      // Renewable energy
      "\"RenewableEnergy\" sector plays a decisive role in combating climate change globally. Solar and wind energy provided 30% of the global electricity supply in 2024 according to reports. Solar panel technology costs have dropped by 90% over the last decade significantly. To achieve Net-Zero goals, annual investments must reach 4 trillion dollars worldwide. Government policies must continue supporting this critical transition. Many governments offer tax incentives and subsidies to accelerate the shift toward renewable sources. As the cost of wind turbines and solar panels keeps falling, even ordinary households can afford this technology. Advances in energy storage batteries also guarantee continuous electricity even after the sun sets.",
      // Remote work
      "\"RemoteWork\" model has fundamentally transformed corporate culture across the global workforce. Following the pandemic, approximately 35% of professionals continue working from home full-time. Tools like Slack, Zoom, and AsyncCommunication enable effective team collaboration daily. However, the blurring boundary between work and rest increases burnout risk by 25%. Effective time management and clear KPIs remain the critical success factors here. Regular video meetings reduce the distance between team members and strengthen trust. Setting up a dedicated workspace at home significantly helps with focus. Many companies now prefer a hybrid model, giving employees both flexibility and a sense of team connection.",
      // Health tech
      "\"HealthTech\" sector has completely reshaped modern medical services around the world. Telemedicine and WearableDevices enable real-time patient health monitoring at any moment. AI-Diagnostic systems have achieved 95% accuracy in cancer detection cases. Healthcare investments exceeded 600 billion dollars in 2025 alone according to reports. Personalized Medicine is recognized as the primary direction of future healthcare development. Remote consultations with doctors are especially useful for people living in rural areas. Smart watches and fitness trackers help continuously monitor heart rate, sleep quality, and physical activity. This data allows doctors to assess a patient's condition more accurately and detect illness earlier. Personalized treatment plans powered by artificial intelligence are expected to become far more common in the future.",
      // Climate change
      "\"ClimateChange\" represents one of the most serious tests facing modern humanity. Reducing CarbonFootprint and adopting Sustainable Practices cannot be postponed. Global temperature has risen 1.2°C since 1850 and may reach 2°C by 2050. EV (Electric Vehicle) sales increased by 18% during 2024 worldwide. The Green Economy represents the only viable path forward for our shared future. Melting glaciers are causing sea levels to rise, posing a serious threat to coastal cities. Many governments are expanding tree-planting programs to help restore forests. Everyone can contribute by reducing daily plastic use and relying more on public transportation. Preserving a clean planet for future generations is a shared responsibility.",
    ],
  },
  ru: {
    easy: [
      // Здоровье
      "вода это жизнь и тело нужда в ней каждый день пей воду чтобы быть бодрым и сильным если воды мало ты устаешь и слабеешь восемь стаканов в день это норма для всех вода помогает коже мозгу и сердцу она делает тебя свежим и полным сил пей чистую воду каждый день это простой путь к здоровью и силе старайся пить воду медленно а не залпом это помогает организму усваивать ее лучше утренний стакан воды заряжает бодростью на весь день",
      // Учеба
      "учиться значит расти и мы можем расти всю жизнь читай книги смотри видео узнавай новое каждый день твой мозг любит новые факты и идеи когда учишься ты становишься умнее записывай важное и повторяй позже это помогает запомнить все что узнал учись хотя бы немного каждый день со временем ты увидишь большой результат делись тем что узнал с друзьями это помогает лучше понять и запомнить материал любопытный ум всегда находит что то новое для изучения",
      // Работа
      "работа это благо для ума и души когда трудишься чувствуешь гордость за себя начни день с плана и следуй ему делай малые шаги и большие дела придут отдыхай когда надо но не сдавайся держи место чистым а мысли ясными работай умно а не только много каждое дело это победа для тебя хорошая команда помогает достигать большего вместе планируй заранее и работа станет намного проще и приятнее маленькие перерывы в течение дня помогают сохранить силы и ясность мысли",
      // Природа
      "природа вокруг нас и она дает нам жизнь деревья дают воздух и тень вода течет в реках и поит все живое проводи время на улице дыши свежим воздухом гуляй в парке или сиди у озера природа помогает расслабиться и найти покой береги землю и держи ее чистой для нас и для тех кто придет после сажай деревья когда можешь это лучший подарок для будущих поколений чистый воздух и чистая вода нужны каждому живому существу",
      // Привычки
      "хорошие привычки делают жизнь легче вставай в одно время каждый день и ложись вовремя ешь полезную еду и двигай телом читай немного и отдыхай когда устал эти малые дела складываются со временем плохие привычки тянут вниз но ты можешь их изменить шаг за шагом начни сегодня и продолжай скоро ты почувствуешь перемены маленькие ежедневные шаги со временем приводят к большим переменам будь терпелив к себе и не сдавайся никогда результат обязательно придет",
      // Сон
      "хороший сон это основа здоровья ложись спать и вставай в одно и то же время каждый день если мало спишь тело устает мозг плохо работает внимание падает убери телефон перед сном читай книгу или просто отдыхай пусть в комнате будет темно и прохладно спи семь или восемь часов хороший сон дает свежую силу для нового дня прогулка перед сном тоже помогает быстрее уснуть и крепче спать всю ночь теплый душ вечером также успокаивает тело и разум",
      // Дружба
      "настоящий друг это самое ценное в жизни хороший друг радуется с тобой и помогает в трудные минуты не лги другу если дал слово держи уважай и умей слушать если друг ошибся не отворачивайся скажи правду и пожелай добра дружба растет с годами новых друзей найти легко а старых трудно поэтому цени каждого друга хороший друг рядом даже в трудную минуту звони и пиши чаще не жди особого повода прощай мелкие ошибки ведь никто не совершенен",
      // Семья
      "семья это самое ценное в жизни пусть в доме будет любовь и забота родители должны уделять время детям говорить и слушать ешьте вместе каждый день спрашивай как прошел день помогай в трудные моменты в семье нужны уважение и терпение дети учатся в семье будь хорошим примером сильная семья делает сильной жизнь говори спасибо за каждый день проводите выходные вместе это укрепляет связь между всеми членами семьи уважай старших и учи детей делать то же самое",
      // Спорт
      "спорт делает тело и ум сильнее двигайся немного каждый день бег ходьба или плавание полезны спорт снимает стресс и улучшает настроение когда тело здоровое работа тоже идет лучше сделай движение привычкой даже полчаса в день достаточно сильные мышцы и крепкое сердце приходят с регулярной практикой это дает свежую силу для нового дня разминка перед тренировкой снижает риск травмы а командный спорт укрепляет дружбу пей воду во время занятий чтобы избежать усталости",
      // Путешествия
      "путешествие лучший способ узнать мир в новом месте ты узнаешь новое видишь природу знакомишься с людьми и пробуешь местную еду у каждого города свой характер перед поездкой составь план и возьми нужное трать деньги с умом снимай фото на память путешествие открывает ум и освежает душу каждый день дарит новый опыт бери с собой легкий багаж это делает поездку намного удобнее и легче местный транспорт помогает узнать город намного ближе",
    ],
    medium: [
      // Здоровье и спорт
      "Физические упражнения необходимы для здорового образа жизни, потому что тело нуждается в регулярном движении. Когда вы занимаетесь спортом постоянно, сердце становится сильнее и энергия растет. Утренние пробежки или вечерние прогулки улучшают настроение и снижают стресс. После тренировки позвольте телу отдохнуть и восстановиться. Фитнес полезен как для тела, так и для духа. Занимайтесь минимум три раза в неделю, и вы заметите положительные изменения. Правильное питание и достаточный отдых значительно усиливают эффект от тренировок. Терпение и постоянство всегда приводят к хорошему результату.",
      // Образование
      "Обучение это путь длиною в жизнь, который никогда не заканчивается. Каждый день дает возможности для получения новых знаний. Чтение книг, просмотр видео или практика помогают расти. Главное это повторять изученное, потому что повторение укрепляет память. Учителя могут направлять, но основной труд должен исходить от вас. Образование это инвестиция в будущее, цените его и стремитесь к знаниям. Каждый человек должен найти свой собственный способ обучения, одни лучше воспринимают информацию на слух, другие через письмо. Регулярная практика укрепляет любой навык.",
      // Управление временем
      "Время это наш самый ценный ресурс, потому что его нельзя вернуть. Планирование дня помогает достигать больше целей эффективно. Приоритизируйте важные задачи, а мелкие оставьте на потом. Социальные сети отнимают много времени, поэтому установите границы. Утро часто самое продуктивное время для сложной работы. Вечер предназначен для отдыха и подготовки к следующему дню. Короткие перерывы в течение дня освежают внимание и уменьшают усталость. Тот, кто планирует день заранее, никогда не теряет время впустую и быстрее достигает своих целей.",
      // Постановка целей
      "Без четких целей жизнь похожа на корабль без направления. Ставьте конкретные задачи и работайте над ними каждый день. Разбивайте большие цели на маленькие этапы для удобства. Проверяйте результаты еженедельно и корректируйте подход. Записывайте цели и держите их на виду как напоминание. Упорство через трудности ведет к успеху. Те кто достигает целей обретают уверенность и покоряют новые вершины. Обсуждение своих целей с близкими людьми повышает ответственность и помогает не сдаваться. Каждая маленькая победа приближает к большой цели.",
      // Питание
      "Правильное питание это основа хорошего здоровья, потому что тело работает на качественном топливе. Употребляйте больше овощей и фруктов для получения витаминов. Избегайте фастфуда и сладостей, они вредят здоровью. Пейте достаточно воды в течение дня. Ешьте медленно и тщательно пережевывайте для лучшего пищеварения. Избегайте тяжелой еды перед сном. Здоровое питание дает энергию и предотвращает болезни. Жирная и жареная пища вредит здоровью сердца, поэтому стоит есть ее реже. Несколько небольших приемов пищи в течение дня улучшают обмен веществ.",
      // Технологии
      "Современные технологии значительно изменили нашу повседневную жизнь. Через смартфоны и интернет мы получаем информацию за секунды, общаемся с друзьями по всему миру и осваиваем новые навыки. Онлайн курсы позволяют получать качественное образование из дома. Однако слишком много времени перед экраном вредит здоровью. Если использовать технологии с пользой, можно сэкономить время и силы. Постоянно изучайте новые инструменты и приложения. Разумное использование социальных сетей помогает избежать лишних отвлечений. Любое устройство создает удобство, но управлять им должен именно человек.",
      // Изучение языка
      "Изучение нового языка требует терпения и постоянной практики. Если заниматься хотя бы десять минут каждый день, словарный запас значительно растет. Слушание, чтение, говорение и письмо четыре важных навыка, которые должны развиваться вместе. Разговор с носителями языка самый быстрый путь к беглости. Фильмы и песни на изучаемом языке тоже помогают понимать. Через ежедневную практику вы достигнете своих целей и обретете уверенность. Использование новых слов в предложениях помогает быстрее запомнить их. Не бойтесь ошибаться, ведь каждая ошибка помогает лучше освоить язык.",
      // Управление стрессом
      "Стресс неизбежная часть современной жизни, но его влияние можно значительно уменьшить. Глубокое дыхание и медитация успокаивают нервную систему. Прогулки на природе и солнечный свет улучшают настроение. Когда записываешь проблемы на бумагу, они кажутся меньше. Достаточный сон и здоровая пища снижают гормоны стресса. Разговор с близкими облегчает душу. Регулярные занятия спортом один из самых эффективных способов справиться с тревогой. Несколько минут тихого дыхания в течение дня успокаивают разум. Разделение работы на небольшие части заметно снижает ощущаемое напряжение.",
      // Новые навыки
      "Освоение нового навыка один из важнейших аспектов личностного роста. Каждое изученное умение открывает новые возможности в жизни. На начальном этапе важнее всего терпение, ведь первые результаты появляются не сразу. В интернете полно бесплатных уроков и видео, только ищите. Если заниматься всего тридцать минут каждый день, через месяц увидите заметный прогресс. Новые навыки расширяют карьерные возможности и обогащают жизнь. Советы других людей вместе с самостоятельной практикой ускоряют обучение. Освоение нового навыка также укрепляет уверенность в себе.",
      // Экономия денег
      "Грамотное управление деньгами основа здоровой жизни. Сделайте привычкой откладывать хотя бы десять процентов от месячного дохода. Избегайте лишних покупок и импульсивных финансовых решений. Записывайте все свои расходы, чтобы понимать куда уходят деньги. Перед магазином составляйте список покупок и покупайте только то, что в списке. Создание резервного фонда ведет к финансовой свободе и дарит спокойствие. Учет даже мелких расходов приводит к заметной экономии. Разумное отношение к деньгам готовит человека к неожиданным трудностям в будущем.",
    ],
    hard: [
        // Продуктивность
      "\"ГлубокаяРабота\" методология направлена на оптимизацию интеллектуального труда в условиях постоянных отвлечений. Исследования показывают, что многозадачность снижает продуктивность на 40%. Внедрение 2-часовых сессий концентрации, использование техники \"Помодоро\" и практика цифрового детокса доказали свою эффективность. Отслеживание ПоказателейСкоростиПечати и проведение еженедельных ретроспектив помогают специалистам постоянно улучшать рабочие процессы. Отключение уведомлений на рабочем месте также помогает сосредоточиться. Каждому специалисту стоит определить свои самые продуктивные часы и планировать сложные задачи именно на это время. Непрерывная работа увеличивает усталость, поэтому рекомендуется короткий перерыв каждые 90 минут.",
      // Искусственный интеллект
      "\"ИскусственныйИнтеллект\" технология представляет собой основу современных инноваций. Благодаря МашинномуОбучению и НейроннымСетям компьютеры решают все более сложные задачи. Гиганты индустрии включая ОупенАйАй и Гугл инвестировали более 10 миллиардов долларов в развитие ИИ. Эти технологии создают революционные изменения в медицине, финансах и ПользовательскомДизайне, одновременно поднимая важные этические вопросы. Кроме того, многие компании теперь используют чат-ботов для обслуживания клиентов, что значительно снижает расходы. Эксперты считают, что в течение следующих десяти лет многие профессии могут полностью измениться благодаря искусственному интеллекту. При этом вопросы авторских прав и конфиденциальности данных остаются актуальными.",
      // Финансовая грамотность
      "\"ФинансоваяГрамотность\" включает навыки необходимые для эффективного управления личными финансами. Понимание бюджетирования, инвестиционных стратегий и пассивного дохода критически важно. Эксперты рекомендуют откладывать 20% дохода и поддерживать резервный фонд на 3-6 месяцев. Принцип сложного процента демонстрирует как капитал значительно растет в долгосрочной перспективе. Большинство людей не начинают откладывать деньги в молодости, из-за чего позже сталкиваются с финансовыми трудностями. Составление ежемесячного бюджета и распределение расходов по категориям значительно облегчает финансовый контроль. Избегание долгов и покупка только необходимого важны для долгосрочной стабильности.",
      // Психология
      "\"ЭмоциональныйИнтеллект\" играет ключевую роль в межличностных отношениях и профессиональных достижениях. Исследования показывают что ЭмоциональныйКоэффициент предсказывает жизненные результаты точнее чем традиционный ИнтеллектуальныйКоэффициент. Компоненты включая самосознание, эмпатию и управление стрессом можно систематически развивать. Данные показывают что люди с высоким ЭмоциональнымКоэффициентом зарабатывают примерно на 58% больше своих коллег. Если эмоциональной осознанности обучают с детства, во взрослой жизни строить успешные отношения становится легче. Руководители с высоким эмоциональным интеллектом быстрее завоевывают доверие своей команды. Понимание чувств других людей помогает мирно разрешать конфликты.",
      // Цифровой маркетинг
      "\"ЦифровойМаркетинг\" стратегия является фундаментальным компонентом современного бизнеса. Через ПоисковуюОптимизацию, МаркетингВСоцсетях и КонтентМаркетинг бренды достигают миллионов потенциальных клиентов. СплитТестирование и аналитика могут повысить эффективность кампаний в 3 раза. Расчет ОкупаемостиИнвестиций и мониторинг КлючевыхПоказателейЭффективности составляют основную задачу профессиональных маркетологов, поскольку РешенияОснованныеНаДанных определяют успех. Email-маркетинг остается одним из самых дешевых и эффективных методов, поскольку он создает прямую связь с клиентом. Сотрудничество с блогерами в социальных сетях помогает брендам быстрее охватывать молодую аудиторию. Успешная кампания требует четкого определения целевой аудитории, а затем адаптации контента под нее.",
      // Кибербезопасность
      "\"Кибербезопасность\" сфера считает защиту данных главной задачей. ДвухФакторная аутентификация и сильные пароли защищают аккаунты от хакеров. Исследования показывают, что 80% атак происходят из-за человеческой ошибки. Фишинг и программы-вымогатели наносят ущерб более 6 триллионов долларов в год. Шифрование и регулярное резервное копирование единственный надежный путь защиты. Поэтому каждому пользователю следует использовать сложные и уникальные пароли, а также регулярно их обновлять. Избегание подозрительных ссылок и внимательная проверка адреса электронной почты являются простым, но эффективным способом защиты. Компании, которые регулярно обучают сотрудников кибербезопасности, помогают заранее выявлять потенциальные угрозы.",
      // Возобновляемая энергия
      "\"ВозобновляемаяЭнергия\" сектор играет решающую роль в борьбе с изменением климата. Солнечная и ветровая энергия обеспечили 30% мирового электроснабжения в 2024 году. Стоимость солнечных панелей снизилась на 90% за последнее десятилетие. Для достижения цели Net-Zero, ежегодные инвестиции должны достичь 4 триллионов долларов. Многие правительства предлагают налоговые льготы и субсидии для ускорения перехода на возобновляемые источники. По мере снижения стоимости ветряных турбин и солнечных панелей даже обычные семьи могут позволить себе эту технологию. Развитие аккумуляторных батарей также гарантирует бесперебойное электроснабжение даже после захода солнца.",
      // Удаленная работа
      "\"УдаленнаяРабота\" модель кардинально изменила корпоративную культуру. После пандемии 35% специалистов продолжают работать из дома. Инструменты Slack, Zoom и AsyncCommunication обеспечивают командное взаимодействие. Однако размытая граница между работой и отдыхом увеличивает риск выгорания на 25%. Управление временем и четкие KPI главные факторы успеха. Регулярные видеовстречи сокращают дистанцию между членами команды и укрепляют доверие. Организация отдельного рабочего места дома значительно помогает сосредоточиться. Многие компании теперь предпочитают гибридную модель, которая дает сотрудникам и гибкость, и чувство командной связи.",
      // Цифровая медицина
      "\"ЦифроваяМедицина\" сектор полностью изменил современные медицинские услуги во всем мире. Telemedicine и WearableDevices позволяют отслеживать здоровье пациентов в реальном времени. AI-диагностические системы достигли 95% точности в обнаружении рака. Инвестиции в здравоохранение превысили 600 миллиардов долларов в 2025 году. Персонализированная медицина признана главным направлением будущего. Удаленные консультации с врачами особенно полезны для жителей сельской местности. Умные часы и фитнес-браслеты помогают непрерывно отслеживать частоту сердечных сокращений, качество сна и физическую активность. Эти данные позволяют врачам точнее оценивать состояние пациента и раньше выявлять заболевания.",
      // Изменение климата
      "\"ИзменениеКлимата\" одно из самых серьезных испытаний современного человечества. Сокращение CarbonFootprint и внедрение Sustainable Practices нельзя откладывать. Глобальная температура выросла на 1.2°C с 1850 года и может достичь 2°C к 2050. Продажи EV (Electric Vehicle) выросли на 18% в 2024 году. Зеленая экономика единственный жизнеспособный путь будущего. Таяние ледников приводит к повышению уровня моря, создавая серьезную угрозу для прибрежных городов. Многие государства расширяют программы посадки деревьев для восстановления лесов. Каждый человек может внести вклад, сокращая ежедневное использование пластика и чаще пользуясь общественным транспортом.",
],
  },
};

/**
 * Get test text based on language and difficulty
 * For word-based tests, returns enough words to meet the requirement
 * For time-based tests, returns a long enough text
 */
export function getTestText(
  language: Language,
  difficulty: Difficulty,
  isWordBased: boolean,
  targetCount: number,
  topic?: string
): string {
  // When a topic is supplied (programmatic-SEO landing pages route here via ?topic=),
  // pull from the topic-specific pack instead of the per-language default set.
  const texts = topic && topicTexts[topic]
    ? topicTexts[topic][difficulty]
    : sampleTexts[language][difficulty];
  // Randomly select one topic from the array
  const randomIndex = Math.floor(Math.random() * texts.length);
  const baseText = texts[randomIndex];

  console.log(`[getTestText] Language: ${language}, Difficulty: ${difficulty}, Topic: ${topic ?? "default"}, Index: ${randomIndex}/${texts.length}`);

  if (isWordBased) {
    // For word-based tests, repeat text until we have enough words
    const words = baseText.split(/\s+/);
    const requiredWords: string[] = [];

    while (requiredWords.length < targetCount) {
      requiredWords.push(...words);
    }

    return requiredWords.slice(0, targetCount).join(" ");
  } else {
    // For time-based tests, repeat text to ensure there's enough
    // Average typing speed is ~40 WPM, so for 60s we need ~40 words minimum
    const estimatedWords = Math.ceil((targetCount / 60) * 50); // 50 WPM estimate
    const words = baseText.split(/\s+/);
    const requiredWords: string[] = [];

    while (requiredWords.length < estimatedWords) {
      requiredWords.push(...words);
    }

    return requiredWords.join(" ");
  }
}
